### ISSUE TITLE
Implement puppy details page

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#11]
As a user I want to see puppy details as I tap on the listing (main and favorites)

AC:
- [x] 1. Image of the puppy should be presented with hero animation and sliver effect.
- [x] 2. Name of the puppy should be presented
- [x] 3. Characteristics (description) of the puppy should be presented
- [x] 4. Breed of the puppy should be presented
- [x] 5. The user should be able to mark the puppy as favorite
- [x] 5.1 All lists (main and favorites) should be updated accrodingly
- [x] 6. The user should be able to access puppy edit page 
- [ ] 7. All the tests below should be imlemented
- [ ] 7.2. Integration (e2e) tests 

Improvements:
- [x] 1. UI Improvements
- [x] 2. Code refinement
- [x] 2.1. Stick to the arch
- [x] 2.2 Make the UI Layer clean

**Comment by DDavidPrime** [comment]
Since the linked PR request is merged, I assume that this issue is fixed. So I'm closing it. If this is not the case, please feel free to reopen this ticket.
