### ISSUE TITLE
how can i generate code without using "rx_bloc_generator" library ?

### ISSUE THREAD

**Issue by hoangchungk53qx1** [Prime-Holding/rx_bloc#246]
how can i generate file [file-name].rxb.g.dart without using library?
example : [file-name].rxb.g.dart 
Thanks

**Comment by DDavidPrime** [comment]
Hi @hoangchungk53qx1 .

The `rx_bloc_generator` package was intended to be used together with the `rx_bloc` package in order to reduce boilerplate code you would usually be required to write.

Currently there is no other recommended way of generating those files rather than running the builder.

**Comment by hoangchungk53qx1** [comment]
thank you.
