### ISSUE TITLE
flutter_rx_bloc package new widgets proposal

### ISSUE THREAD

**Issue by DDavidPrime** [Prime-Holding/rx_bloc#285]
The `flutter_rx_bloc` package has a great number of quality widgets for the purposes of building and reacting to changes that occur in the rx_blocs. They are easy to use and can be placed anywhere in the widget tree.

Throughout different projects we've come across the need to create custom widgets that usually are result of nesting the basic components such as `RxBlocBuilder`,`RxBlocListener` or similar. Hereby I propose an idea for three new (convenience) widgets that I think would be a nice addition to the `flutter_rx_bloc` package.

### RxBlocMultiListener
RxBlocMultiListener widget is a widget inspired from [MultiBlocListener](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/MultiBlocListener-class.html) which takes multiple `RxBlocListener` widgets and nests them above a specific child widget for making the code more readable and not have multiple nested widgets one inside the other. It would serve as a place where the user can define multiple listeners listening to states of a specific bloc without having to define them in different places throughout the widget tree.

### RxBlocMultiBuilder
Similarly to the `RxBlocMultiListener`, `RxBlocMultiBuilder` would be the same counterpart which instead of a listener has a build function. 

In more complex use cases, the UI sometimes depends on multiple different states which are provided separately. Sometimes, we want to render the UI once we have all of the states properly retrieved. Currently without this implementation we would need to do it with nesting multiple RxBlocBuilder widgets like this:

```dart
RxBlocBuilder<SomeBlocType>(
  state: (bloc) => bloc.states.state1,
  builder: (context, state1Snapshot, bloc) 
    => RxBlocBuilder<SomeBlocType>(
      state: (bloc) => bloc.states.state2,
      builder: (context, state2Snapshot, bloc) 
        => MyWidget(state1Snapshot,state2Snapshot),
      ),
)
```

This can fairly increase in complexity for each subsequent nested RxBlocBuilder, since we'd need to include it nested in the right position in the widget tree, provide the new state and its name and as well provide all the states to the widget(s) which are under them.

With `RxBlocMultiBuilder` we could do something like this:

```dart
RxBlocMultiBuilder<SomeBlocType>(
  states: (bloc) => [
    bloc.states.state1,
    bloc.states.state2,
    // ...
  ],
  builder: (context, statesData, bloc) => MyWidget(statesData)
)
```

In this case we just define a list of states for which we want to keep track of. Once all of the states emit some data, the builder method is executed. For each subsequent change in any of those states, the builder method is executed with the updated data. In this case the `statesData` parameter can be a list of `AsyncState`s or a custom type that contains all of that data.

### Error catching widget

We could include a widget or mechanism that would allow to catch any kind of exceptions from the provided bloc and perform a callback (RxBlocExceptionListener, RxBlocExceptionBuilder). By default the builder would connect to the blocs `errorState` and listen for all exceptions that enter the sink. The benefit of using it would be the possibility to selectively react to any kind of exception that occurs and perform custom logic. Additionally, exceptions thrown from the bloc would be much easier to localise from the UI, rather than having custom logic that happens inside the bloc.

Any kind of suggestions or discussions around this widget are open, since it is in its idea stage.

---

Notes:

- All of the mentioned widgets are subject to discussion. Everyone is encouraged to participate in it with their ideas, suggestions and criticism (positive and negative).

**Comment by StanevPrime** [comment]
@DDavidPrime the only challenge I see here is the type safety, so how you approach this?

**Comment by StanevPrime** [comment]
This feature is already added to the flutter_rx_bloc - https://pub.dev/documentation/flutter_rx_bloc/latest/flutter_rx_bloc/RxBlocMultiBuilder2-class.html
