### ISSUE TITLE
[Web] Reduce the http calls being made on tab switch

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#305]
![Image](https://user-images.githubusercontent.com/32831935/184854177-8fe29490-b147-4992-a558-ccc197f15870.png)

Currently when switching between the Dashboard and Reminder list pages the application makes 5 http requests. Please try to reduce them to minimum

**Comment by viktorAngelievPrime** [comment]
When creating a request there is a "subscribtion" that notfies the front-end when any changes are done.
Here is one requests data:

**Comment by viktorAngelievPrime** [comment]
When creating a request to firebase there is "subscribtion" that notifies the front end for any database changes.
Here is request data for one of the HTTP requests. There are 3 total HTTP requests - for reminders and 2 for counters
![image](https://user-images.githubusercontent.com/110596478/185076933-08b61a25-2414-4b10-849c-e0183ec8c4f3.png)
When switching pages there now must be 6 requests - 3 for data and 3 notifying firebase to stop sending notifications about database changes for the previous request.
![image](https://user-images.githubusercontent.com/110596478/185077724-d65f9991-d5e4-40f8-880d-789bd03f0595.png)
