### ISSUE TITLE
[Web] Set the date of creating and updating to have hours, minutes etc.

### ISSUE THREAD

**Issue by StanislavPrime** [Prime-Holding/rx_bloc#327]
For the 3 cases:
- The initial generation of the reminders when a user is logged in for the first time.
- When a date of a reminder is updated.
- When a reminder is created.
Set the hours, minutes, seconds, milliseconds, microseconds -  which are the current values from DateTime.now();

**Comment by viktorAngelievPrime** [comment]
WEB Done
