### ISSUE TITLE
rx_bloc_list - blocks usage of fresh flutter_rx_bloc dependency

### ISSUE THREAD

**Issue by PankovSerge** [Prime-Holding/rx_bloc#333]
Because of strict version constraints of rx_bloc_list dependency for flutter_rx_bloc: 
`flutter_rx_bloc: ^4.0.0` [pubspec.yaml](https://github.com/Prime-Holding/rx_bloc/blob/develop/packages/rx_bloc_list/pubspec.yaml) which allow to use only range of versions >=4.0.0 <5.0.0 it's not possible to have rx_bloc_list and fresh version (5.0.2) of flutter_rx_bloc dependency at the same time.

**Comment by StanevPrime** [comment]
It looks like we need to release a new version of the rx_bloc_list to catch up with the breaking changes of the flutter_rx_bloc
