### ISSUE TITLE
Add Apple as a social login in the Login Page

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#373]
As a developer I want to have the Apple login setup (default: false) so that I can speed up the social login integration

ACs:

- Login with Apple button in the login form
- Pre-configured functionality 
- Added as an option in the rx_bloc_cli create command (by default false)

**Comment by kostadin-damyanov-prime** [comment]
@StanevPrime @PrimeSwiftArt I would argue that all 3-rd party integrations (including this one) should be off by default. They should be enabled only if the user explicitly requests them using the create command.

**Comment by StanevPrime** [comment]
Yes, I agree with your suggestion. The ACs have been updated accordingly.

**Comment by kostadin-damyanov-prime** [comment]
Integrating with apple sign-in is implemented by a dedicated package so there is no need to include it in the rx_bloc_cli package.

References:
* https://firebase.google.com/docs/auth/flutter/federated-auth
* https://pub.dev/packages/sign_in_with_apple
