### ISSUE TITLE
Add Google as a social login in the Login Page

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#374]
As a developer I want to have the Google login setup (default: false) so that I can speed up the social login integration

ACs:

- Login with Google button in the login form
- Pre-configured functionality 
- Added as an option in the rx_bloc_cli create command (by default false)

**Comment by kostadin-damyanov-prime** [comment]
Integrating with google sign-in is implemented by a dedicated package so there is no need to include it in the rx_bloc_cli package.

References:
* https://firebase.google.com/docs/auth/flutter/federated-auth
* https://pub.dev/packages/google_sign_in
