### ISSUE TITLE
Analyse the popular state management solutions such as bloc, riverpod etc and propose feature requests in the rx_bloc ecosystem

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#402]
As a product owner I want the popular state management solutions to be analysed and compared with the rx_bloc ecosystem so that we can spotlight missing features

- Analyse the following ecosystems
-- [bloc](https://pub.dev/packages/bloc)
-- [Riverpod](https://pub.dev/packages/riverpod)
-- [GetX](https://pub.dev/packages/get)
-- [Redux](https://pub.dev/packages/redux) 
- Create feature suggestions for the rx_bloc ecosystem based on the outcome of AC 1

Estimate: 4d

**Comment by DDavidPrime** [comment]
As discussed, @nikolay-vasilev-prime will be taking bloc and Riverpod, while I (@DDavidPrime ) will be looking into GetX and Redux.

**Comment by StanevPrime** [comment]
Step 1: Use the `@RxCoordinatorBloc()` annotation to enable coordinator-specific code generation
```
@RxCoordinatorBloc()
class CoordinatorBloc extends $CoordinatorBloc {}
```

Step 2: Annotate the states that should be available in the coordinator bloc
```
abstract class ProfileBlocStates {
  @RxCoordinatorAware()
  Stream<ProfileModel> get onProfileChanged;
}
```

## Use cases
### Use case 1: Use interceptors for debugging purposes through logs

```
class AppDependencies{

  /// List of all providers used throughout the app and register the interceptors 
  late List<SingleChildWidget> providers = [
     ...
     _coordinatorBlocs,
  ];

  List<SingleChildWidget> get _coordinatorBlocs => [
        RxCoordinatorBlocProvider<CoordinatorBlocType>(
          create: (context) => CoordinatorBloc(),
          interceptors: (bloc) => [
            [
              // Every annotated state will be printed for debugging purposes
              // Example: ProfileBlocStates.onProfileChanged: {name: "Georgi Stanev"}
              if (kDebugMode) RxBlocLogger(bloc), 
            ],
          ],
        ),
      ];
}
```
### Use case 2: Use the generated states in the other blocs

```
@RxBloc()
class DashboardBloc extends $DashboardBloc {
    DashboardBloc(this._coordinatorBloc);

    /// The DashboardBloc can listen for the following state:  _coordinator.profile.onProfileChanged
    final CoordinatorBlocType _coordinator
}
```
