### ISSUE TITLE
Build a showcase brick for the QR Scanner

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#420]
As a developer, I want to be able to create projects using the rx_bloc_cli with the QR scanner showcase feature. The feature should use widget_toolkit_qr package

ACs
- [x] Implement new brick that contains the code necessary for creating a QR scanner showcase feature
- [x] Added as an option in the rx_bloc_cli create --enable-feature-qr-scanner command (by default false)

Estimate: 1d

**Comment by DDavidPrime** [comment]
As per [#17](https://github.com/Prime-Holding/widget_toolkit/issues/17) being marked as complete, this should be unblocked now.

**Comment by StanevPrime** [comment]
@JvnSlv to add description and ACs

**Comment by nikolay-vasilev-prime** [comment]
I tested the testapp and the QR showcase is working
