### ISSUE TITLE
Build a brick for the DevMenu

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#421]
- [ ] The source code should be deleted from gitlab once is migrated to github
- [x] The main read me file needs to be updated
- [x] Charles integration
- [x] Firebase Push Notifications integration
- [x] The dev menu should not be visible in the production flavour

**Comment by RomanovaPrime** [comment]
Considered to be a part of the base project, generated with rx_bloc_cli. When  initialize  a project to have it with a flag equal to true (by default), so we will have it by default but users can exclude it if want to.
