### ISSUE TITLE
Add CI/CD option using the Github Actions

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#491]
As a developer I want to create a new project using the rx_bloc_cli with pre-defined CI/CD Github integration so that I can ensure the quality of the app using automated tests as well as quick iteration cycle 

ACs

- [x] Build a CI pipeline for the Booking App
   - [x] This pipeline should run the unit tests
   - [x] This pipeline should trigger when code is pushed to the repository 
- [x] Build a CD pipeline for the Booking App
  - [x] This pipeline should trigger when a tag with a specific pattern is created
  - [x] Android CD pipeline (build and deploy artefacts to Google Play)
  - [x] iOS CD pipeline (build and deploy artefacts to TestFlight)
- [x] Build a CD/CD brick based on the above ACs
- [x] Add an option to the rx_bloc_cli `--cicd=github`. 
Note: In the near future there will be other integrations such as AzureDev Ops, Fastlane and Code Magic so please build that option with the needed validations in mind

**Comment by DDavidPrime** [comment]
As per a discussion with @StanevPrime and @PrimeSwiftArt , we're going to implement CI/CD using Fastlane.

**Comment by DDavidPrime** [comment]
Remaining: 
- Add header in conditional github section
- Rename to "Build and distribute Booking app"
- Fix iOS build 
- Fix deployment of iOS/Android artifacts to stores

Deadline: 6.11.2023
