### ISSUE TITLE
Include pop event in the router_bloc brick

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#500]
As a developer, I want to be able to navigate using both `push` and `pop` events in the project created with **rx_bloc_cli**. At the moment the generated **router_bloc** contains only `push`.

**Comment by StanevPrime** [comment]
@PetkovPrime, could you please provide some links to the reference implementation in the Todo App ?

**Comment by StanevPrime** [comment]
@StanislavPrime do you have the availability to take this issue ?

**Comment by StanislavPrime** [comment]
Yes, I will start working on it.

**Comment by PetkovPrime** [comment]
As requested, I'm providing a link to one possible implementation: https://gist.github.com/PetkovPrime/0dd80022177b9d806708628bf47fb6c2

Example usage
```dart
_routerBloc.events.pop();
```
