### ISSUE TITLE
Include remote localization infrastructure

### ISSUE THREAD

**Issue by PetkovPrime** [Prime-Holding/rx_bloc#587]
As a developer I would like to have an option to generate a project that has a remote localisation configured.

Acceptance Criteria
- [x] Generated project can use translations fetched from a remote data source.
- [x] Translation data is fetched on app initialisation.
- [x] In cases where there is no data from the remote source (missing localisation, unsupported locale, failed request, etc.) the application should use local translations as fallback.

Developer Notes
- [x] The translation data can be fetched while the Splash screen is presented (on app initialisation)
- [x] The translation data can be stored in-memory, no need for any persistent storage for now.
- [x] The `I18n` class in the generated `assets.dart` supports adding an optional `customLookup` implementation that is called before the generated lookups. It can be used to seamlessly integrate the translation data in the application.

API Contract
```
GET /api/translations
```

Response Body
```
{
    translations: {
        "en_US": {
            "welcomeMessage": "Welcome to the application",
            "loginButtonLabel": "Login"
            ...
        },
        "fr_FR": {
            "welcomeMessage": ...
            "loginButtonLabel": ...
            ...
        },
        ...
    }
}
```

**Comment by PetkovPrime** [comment]
Will be required for an upcoming project

**Comment by StanevPrime** [comment]
Expected PR delivery: 19.10.2023
