### ISSUE TITLE
Firebase Analytics improvements

### ISSUE THREAD

**Issue by PetkovPrime** [Prime-Holding/rx_bloc#588]
As a developer, I would like to have [screenviews](https://firebase.google.com/docs/analytics/screenviews) tracking option inside the generated project.

Acceptance criteria:

Given the project is generated with `analytics` feature enabled
- [ ] When the user is navigated to a screen, then a `screenview` event is sent to the analytics provider.
- [ ] When the user is navigated to a screen that changes multiple pages in the navigation stack (for example by opening a deep link), then a `screenview` event is sent only for the screen presented to the user.

Given the project is generated without `analytics` feature
- [ ] When the user is navigated to a screen, then no analytics tracking should occur

Technical notes:
The `RouterBloc` should use the `CoordinatorBloc` to inform of a screen change. A new `FirebaseAnalyticsBloc` listens for any changes and logs the corresponding `screenview` event.

**Comment by PetkovPrime** [comment]
Will be required for an upcoming project @DDavidPrime

**Comment by StanevPrime** [comment]
Expected PR merge: 17.10.2023
