### ISSUE TITLE
Include step for building and running tests on rx_bloc_cli generated project

### ISSUE THREAD

**Issue by PetkovPrime** [Prime-Holding/rx_bloc#610]
- [x] Include automated project generation with various configurations 
    - [x] All flags enabled
    - [x] All flags disabled
    - [x] Default flags enabled
    - [x] Without showcase features
 - [x] The generated projects should compile and all tests should pass
 - [x] The above pipelines  should run in GitHub

**Comment by StanevPrime** [comment]
Expected open PR : 23.10.2023
