### ISSUE TITLE
Fix onBottomScrolled and onRefresh being executed simultaneously

### ISSUE THREAD

**Issue by PVGeorgievPrime** [Prime-Holding/rx_bloc#622]
When the first page of the paginated list doesn't exceed the device's screen and the user tries pull-to-refresh, that causes `onBottomScrolled` and `onRefresh` callbacks to be executed simultaneously.

How to reproduce:
In the example given in the `rx_bloc_list` you need to change the list items per page to be 5 instead of 50. Then when the first page is loaded try pull-to-refresh. Instead of having a refreshed list  `onBottomScrolled` is called  simultaneously, which causes the second page with another 5 items to be loaded.

**Comment by StanevPrime** [comment]
@DDavidPrime, can you please assist with executing the needed manual tests ?
