### ISSUE TITLE
Add code documentation to the reminders sample

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#623]
As a sales representative I want the reminders to be documented so that I can use it as a showcase to the potential clients

ACs
- [x] Document the Business Layer (Services)
- [x] Document the Business Layer (Bloc)
- [x] Document the Business Layer (Models)
- [x] Document the UI/UX Layer (Widgets - Reusable Components)
- [x] Document the UI/UX Layer (Widgets - Pages)
- [x] Document the Data Layer (Repositories)
- [x] Document the Data Layer (Data Sources)

DevNotes

- Use the Github Co-Pilot to generate the needed documentation

**Comment by StanevPrime** [comment]
@DDavidPrime the budget for this ticket is 16 hours.

**Comment by DDavidPrime** [comment]
Since this ticket wasn't done yet (closed due to a linked PR being merged), I'm reopening this.

#627 This PR handles almost everything except for UI/UX Layer.
The UI/UX Layer will be documented in a separate PR.
