### ISSUE TITLE
Integrate realm into the Reminders App

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#634]
As a developer I want the [realm](https://pub.dev/packages/realm) package to be integrated as a new flavour into the Reminders app so that I can see how it compares to the already implemented Firebase solution.

ACs
- Two flavours should be added to the Reminders app (local storage and cloud storage)
  - Realm Local Storage should be implemented with minimal changes to the cloud solution
  - [Realm Atlas](https://www.mongodb.com/atlas/app-services/device-sync) flexible sync storage to be integrated in to the Reminders app
     - https://www.mongodb.com/pricing the Shared should be used
     - The implementation should support real time updates in the cloud flavour
     - Check if an issue similar to [this](https://github.com/mogol/flutter_secure_storage/issues/592) is presented in realm library
 - The Firebase Authentication should remain unchanged
 - Both flavours should use [encryption](https://www.mongodb.com/docs/realm/sdk/flutter/realm-database/realm-files/encrypt/)
 - The newly added flavours should not amend the established Reminders App Architecture

**Comment by StanevPrime** [comment]
@kostadin-damyanov-prime, please review and adjust the ACs if needed

**Comment by DDavidPrime** [comment]
Closing this ticket as we have decided against integrating realm into the reminders app.
