### ISSUE TITLE
Implement a credentials prompt in the Fastlane and encryption/decryption script

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#636]
As a developer, I want that if the environment variables are absent, the user should be prompted within the build_custom Fastlane to input their values.

ACs
- [x] Env variables prompt
  - [x] Build lane
  - [x] Deploy lane
- [x] encrypt.sh
- [x] decrypt.sg
- [x] Update the documentation
  - [x]  https://github.com/Prime-Holding/rx_bloc/blob/develop/packages/rx_bloc_cli/example/docs/continuous_delivery.md
  - [x] https://github.com/Prime-Holding/rx_bloc/tree/develop/packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_distribution_repository/__brick__
- [x] All related projects (such as the booking app) to use the new version of the Fastlane script

**Comment by kostadin-damyanov-prime** [comment]
@StanevPrime The build and deploy parts are done and merged.
Currently I do not have the time to dedicate to updating the prime projects.
This change only affects manual builds so if we are using CI/CD to build them this does not affect them.
