### ISSUE TITLE
Implement a solution that keeps the native part of the generated Flutter app up-to-date

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#637]
As a developer I want the native part of the project generated by the rx_bloc_cli to be up-to-date all the time so that I can start building the app right away instead of spending time on fixing issues manually

ACs:

- [x] The iOS and Android platforms support are removed from the rx_bloc_cli codebase to ensure they do not get outdated over time
- [ ] Added documentation for extra manual steps including, but not limited to enabling patrol 

Android:
- [x] Research how to add code snippets inside a file, similar to the flavorizr package (target: app/build.gradle)
- [x] Research the XML package (https://pub.dev/packages/xml) and adjust AndroidManifest.xml using it

 iOS:
- [x] Add plists and entitlements during code generation
- [x] Insert firebase setup script (build phase script)
- [x] Conditionally integrate social logins to flavor specific plists
- [ ] Update Patrol section in Readme with reference to official Patrol documentation (configuration of native platforms)

**Comment by DDavidPrime** [comment]
Android:
- [ ] Research how to add code snippets inside a file, similar to the flavorizr package (target: app/build.gradle)
- [ ] Research the XML package (https://pub.dev/packages/xml) and adjust AndroidManifest.xml using it

 iOS:
- [ ] Add plists and entitlements during code generation
- [ ] Insert firebase setup script (build phase script)
- [ ] Validate flavor specific plists and entitlements
- [ ] Update Patrol section in Readme with needed manual steps to get Patrol running
