### ISSUE TITLE
Record a video guide for configuring the CI and CD pipelines by using Github Actions and Fastlane

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#666]
- [x] Create a video guide showcasing the creation and setup of a new project
~- [ ]  Upload the video and reference it in the generated docs~

**Comment by PVGeorgievPrime** [comment]
@StanevPrime  I tested the process and can say that is well documented and works as expected!

**Comment by DDavidPrime** [comment]
Moving the second acceptance criteria to another ticket: #716 .
