### ISSUE TITLE
Integrate objectbox into the Reminders App

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#674]
As a developer I want the [objectbox](https://pub.dev/packages/objectbox) package to be integrated as a new flavour into the Reminders app so that I can see how it compares to the already implemented Firebase solution.

ACs
- Two flavours should be added to the Reminders app (local storage and cloud storage)
  - Objectbox Local Storage should be implemented with minimal changes to the cloud solution
  - ~~[Sync](https://pub.dev/packages/objectbox_sync_flutter_libs) flexible sync storage to be integrated in to the Reminders app~~
     - ~~The implementation should support real time updates in the cloud flavour~~
 - The Firebase Authentication should remain unchanged
 - The newly added flavours should not amend the established Reminders App Architecture

**Comment by DDavidPrime** [comment]
Closing this ticket as we have decided against integrating objectbox into the reminders app.
