### ISSUE TITLE
Using RxBlocProvider with SearchDelegate

### ISSUE THREAD

**Issue by bensonarafat** [Prime-Holding/rx_bloc#675]
Hi 
Please, how can i be able to use RxBlocProvider with SearchDelegate, I checked the examples but there is nothing. 
I will love if you can guide me on this, or show me a code sample 
Thanks

**Comment by StanevPrime** [comment]
Please have a look at the Booking sample and let me know if you have any questions.

https://github.com/Prime-Holding/rx_bloc/blob/feature/github-search-rebuilt/examples/github_search/lib/feature_dashboard/views/dashboard_search_delegate.dart

**Comment by bensonarafat** [comment]
Thanks. @StanevPrime 
This was what i was looking for. 
I'm closing the issue now.
