### ISSUE TITLE
Exclude dependencies from the smart widgets in the golden test

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#700]
As a developer I want when the widget tree is built during the golden tests execution the dependencies of smart widgets such as BloCs, Services etc to be not added to the widget tree so that I can add them as mock objects

ACs
- [x] Find a way to distinguish whether the widgets are built during test execution
- [x] Document the expected behaviour

Reference implementation:

```
class AppTodoListBulkEditPopupMenuButtonWithDependencies {
    @override
    Widget build(BuildContext context) {
        final current =  TodoManagementPage();

        if(isInTestMode) {
            return current;
        }

        return MultiProvider(
            providers: [
              ..._services,
              ..._blocs,
           ],
           child: current,
        );
  }
}
```

**Option 1:** 
flutter_test_config.dart
```
import 'package:procredit/base/app/config/app_constants.dart';
...

Future<void> testExecutable(FutureOr<void> Function() testMain) async =>
    GoldenToolkit.runWithConfiguration(
      () async {
        WidgetsApp.debugAllowBannerOverride = false;
        isInTestMode = true;
        await loadAppFonts();
        return testMain();
      },
      config: GoldenToolkitConfiguration(
        enableRealShadows: true,
      ),
    );
```

**Option 2**

is_in_test_mode_io_available.dart
```
bool isInTestMode = io.Platform.environment.containsKey('FLUTTER_TEST');
```

is_in_test_mode_io_not_available.dart
```
bool isInTestMode = false;
```

app_constants.dart
```
import 'is_in_test_mode.dart' if (dart.io) 'is_in_test_mode_io_available.dart' if (dart.library.html) 'is_in_test_mode_io_not_available.dart';

```

Documentation: https://dart.dev/guides/libraries/create-packages#conditionally-importing-and-exporting-library-files

**Option 3**

Define a variable in the test run command and have it as a global constant with default value in the app,

app_constants.dart
```
import 'dart:io' as io;

// Global flag for test mode
bool isInTestMode = bool.fromEnvironment('testing_mode', defaultValue: false);
```

Run All Tests configuration arguments
```
--dart-define=testing_mode=true
```

Refferance: https://stackoverflow.com/a/63723815

**Option 4**

`Platform.environment.containsKey('FLUTTER_TEST');` is a boolean that returns `true` when it's executed by a test and `false` otherwise.
To work on Web, iOS and Android, it should be imported from `universal_io/io.dart` .It is tested on mobile and web and it works with `universal_io: ^2.2.2`

**Comment by DDavidPrime** [comment]
This could also help with the test checking: https://stackoverflow.com/questions/59028609/how-to-find-if-we-are-running-unit-test-in-dart-flutter

**Comment by nikolay-vasilev-prime** [comment]
`Platform.environment.containsKey('FLUTTER_TEST');` is a boolean that returns `true` when it's executed by a test and `false` otherwise. 
To work on Web, iOS and Android, it should be imported from `universal_io/io.dart` . 
I tested it on mobile and web and it works with `universal_io: ^2.2.2`. 

So the Option 2 with global variable is a good option.

I discovered that if multiple pages/widgets implement the same type of widget with `*WithDependencies`, they share same instance of the widget.

**Comment by StanevPrime** [comment]
Adding an extra dependency (universal_io) is not a good option from my perspective, since it increases the maintenance cost of the rx_bloc_cli.

**Comment by StanevPrime** [comment]
It was decided to proceed with option 2 because of the following benefits

- Less maintenance cost compared with the other solutions
- the `isInTestMode` global variable will be accessible for all kind of tests, including unit and golden ones
- the `isInTestMode` will be set automatically 


@DDavidPrime, @nikolay-vasilev-prime
