### ISSUE TITLE
Upload and reference Github Actions video tutorial

### ISSUE THREAD

**Issue by DDavidPrime** [Prime-Holding/rx_bloc#716]
Currently, we have a video tutorial for the Github CI/CD used in the rx_bloc_cli generated project which is not yet publicly available. Upload it and link it in the generated docs for easier reference.

AC:
- [ ] Upload the video and reference it in the generated docs

**Comment by DDavidPrime** [comment]
@StanevPrime Since we've been discussing that the video tutorial is part of the Udemy Business, do we still want to link the video in the generated docs? I am unsure if everyone will have access to it. How do we proceed with this?

**Comment by StanevPrime** [comment]
The Udemy course is not public so the link here can be skipped in the documentation
