### ISSUE TITLE
Increase coverage in projects generated with rx_bloc_cli

### ISSUE THREAD

**Issue by DDavidPrime** [Prime-Holding/rx_bloc#721]
Projects generated with the rx_bloc_cli currently have a select number of unit tests which result (with all flags enabled) to about 6% in code coverage. Add unit tests to increase code coverage to at least 50%.

ACs:
- [x] Add unit tests for existing functionality in the rx_bloc_cli generated projects
- [ ] The minimum code coverage should be at least 50 for projects with all flags enabled
  - [x] Golden tests for the [login form](https://github.com/Prime-Holding/rx_bloc/blob/develop/packages/rx_bloc_cli/mason_templates/bricks/feature_login/__brick__/lib/feature_login/ui_components/login_form.dart)
  - [x] Analytics [bloc](https://github.com/Prime-Holding/rx_bloc/blob/develop/packages/rx_bloc_cli/mason_templates/bricks/lib_analytics/__brick__/lib/lib_analytics/blocs/analytics_bloc.dart) unit tests
  - [x] [lib_auth](https://github.com/Prime-Holding/rx_bloc/tree/develop/packages/rx_bloc_cli/mason_templates/bricks/lib_auth/__brick__/lib/lib_auth) unit tests
  - [x] [lib_permissions](https://github.com/Prime-Holding/rx_bloc/tree/develop/packages/rx_bloc_cli/mason_templates/bricks/lib_permissions/__brick__/lib/lib_permissions) unit tests
  - [x] [lib_realtime_communication](https://github.com/Prime-Holding/rx_bloc/tree/develop/packages/rx_bloc_cli/mason_templates/bricks/lib_realtime_communication) uni tests
  - [x] [common_ui_components](https://github.com/Prime-Holding/rx_bloc/tree/develop/packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/common_ui_components) golden tests in the base brick
  - [x] extensions [unit tests](https://github.com/Prime-Holding/rx_bloc/tree/develop/packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/extensions) in the base brick
  - [x] error_mappers [unit tests](https://github.com/Prime-Holding/rx_bloc/tree/develop/packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/lib/base/common_mappers/error_mappers) in the main brick
  - [ ] [PIN](https://github.com/Prime-Holding/rx_bloc/tree/develop/packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/lib/lib_pin_code) golden and unit tests (Low priority)
  - [x] [feature_counter](https://github.com/Prime-Holding/rx_bloc/tree/develop/packages/rx_bloc_cli/mason_templates/bricks/feature_counter/__brick__/test/feature_counter) refactor current tests to match the existing convention
- [x] Update `run_app_tests.yaml` github workflow in generated projects to reflect the minimum code coverage
- [x] Move `feature_login` functionality out of `lib_auth`

**Comment by nikolay-vasilev-prime** [comment]
I wasn't able to push the changes and since I'm in PTO, I move the task in To Do.

**Comment by nikolay-vasilev-prime** [comment]
Added AC to refactor existing tests in `feature_counter`

**Comment by nikolay-vasilev-prime** [comment]
[PIN code golden tests](https://github.com/Prime-Holding/rx_bloc/tree/721-increase-coverage-in-projects-generated-with-rx_bloc_cli/packages/rx_bloc_cli/mason_templates/bricks/lib_pin_code/__brick__/test/lib_pin_code/views) fail to generate.

Somehow they were succeeding in [previous commit](https://github.com/Prime-Holding/rx_bloc/pull/818/commits/bb0a86d71a062e084bff9bf6daa51d1e24c0448a) but aren't now when I cloned this exact commit and try to generate the goldens.

@GoranPrime was helping me investigate the issue and suggested to downgrade `widget_toolkit_pin` dependency, but it doesn't work, because it required to Idelete `alice` and downgrade `widget_toolkit_otp`, `widget_toolkit_pin`, `widget_toolkit_biometrics`, `widget_toolkit`, `flutter_rx_bloc`, `rx_bloc_list`, `rx_bloc_generator`, `rx_bloc`, `rx_bloc_test`, `rxdart`.

I'm kinda stuck and would love to receive help from someone with more knowledge on the topic.

The error stack is:

```
Pending timers:
Timer (duration: 0:00:01.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#5      TimerStream._buildController.<anonymous closure> (package:rxdart/src/streams/timer.dart:50:17)
#12     TimerStream.listen (package:rxdart/src/streams/timer.dart:19:31)
#13     _DelayStreamSink.onData (package:rxdart/src/transformers/delay.dart:18:58)
#41     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:197:32)
#42     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:1519:24)
#43     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1033:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 36 frames from dart:async and package:stack_trace)

Timer (duration: 0:00:01.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#5      TimerStream._buildController.<anonymous closure> (package:rxdart/src/streams/timer.dart:50:17)
#12     TimerStream.listen (package:rxdart/src/streams/timer.dart:19:31)
#13     _DelayStreamSink.onData (package:rxdart/src/transformers/delay.dart:18:58)
#41     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:197:32)
#42     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:1519:24)
#43     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1033:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 36 frames from dart:async and package:stack_trace)

Timer (duration: 0:00:01.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#5      TimerStream._buildController.<anonymous closure> (package:rxdart/src/streams/timer.dart:50:17)
#12     TimerStream.listen (package:rxdart/src/streams/timer.dart:19:31)
#13     _DelayStreamSink.onData (package:rxdart/src/transformers/delay.dart:18:58)
#41     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:197:32)
#42     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:1519:24)
#43     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1033:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 36 frames from dart:async and package:stack_trace)

Timer (duration: 0:00:01.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#5      TimerStream._buildController.<anonymous closure> (package:rxdart/src/streams/timer.dart:50:17)
#12     TimerStream.listen (package:rxdart/src/streams/timer.dart:19:31)
#13     _DelayStreamSink.onData (package:rxdart/src/transformers/delay.dart:18:58)
#41     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:197:32)
#42     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:1519:24)
#43     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1033:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 36 frames from dart:async and package:stack_trace)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1542 pos 12: '!timersPending'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1542:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1049:7)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from class _AssertionError and package:stack_trace)

The test description was:
  create_pin_empty - light
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: create_pin_empty - light


```

**Comment by GoranPrime** [comment]
@nikolay-vasilev-prime I've already found [the issue](https://github.com/Prime-Holding/widget_toolkit/blob/develop/packages/widget_toolkit_pin/lib/src/lib_pin_code_with_biometrics/blocs/pin_code_bloc.dart#L81), it'll just take a little longer to fix since it would most likely require a bigger refactor of `widget_toolkit_pin`, which is already a separate task:
https://github.com/Prime-Holding/widget_toolkit/issues/130

The issue was introduced in the 0.2.1 release of `widget_toolkit_pin` released yesterday, it's not present in 0.2.0 which has the same dependencies. If it was asking you to downgrade those, it sounds like you tried to go back to 0.1.0?

The reason I told you to try the downgrade to 0.2.0 and leave a note to update it later was to not block this task while I'm resolving the issue, not as a long term fix.

**Comment by nikolay-vasilev-prime** [comment]
> [@nikolay-vasilev-prime](https://github.com/nikolay-vasilev-prime) I've already found [the issue](https://github.com/Prime-Holding/widget_toolkit/blob/develop/packages/widget_toolkit_pin/lib/src/lib_pin_code_with_biometrics/blocs/pin_code_bloc.dart#L81), it'll just take a little longer to fix since it would most likely require a bigger refactor of `widget_toolkit_pin`, which is already a separate task: [Prime-Holding/widget_toolkit#130](https://github.com/Prime-Holding/widget_toolkit/issues/130)
> 
> The issue was introduced in the 0.2.1 release of `widget_toolkit_pin` released yesterday, it's not present in 0.2.0 which has the same dependencies. If it was asking you to downgrade those, it sounds like you tried to go back to 0.1.0?
> 
> The reason I told you to try the downgrade to 0.2.0 and leave a note to update it later was to not block this task while I'm resolving the issue, not as a long term fix.

The PR uses version 0.2.0 -> https://github.com/Prime-Holding/rx_bloc/blob/721-increase-coverage-in-projects-generated-with-rx_bloc_cli/packages/rx_bloc_cli/mason_templates/bricks/rx_bloc_base/__brick__/pubspec.yaml

**Comment by GoranPrime** [comment]
You have to remove the `^`:
`widget_toolkit_pin: 0.2.0`

Fun fact: writing it as `^0.2.0` is the same as `>=0.2.0 <0.3.0`, so essentially telling it to fetch the latest non-breaking update... which in this case is 0.2.1, which you helped publish 2 days ago 😆

**Comment by nikolay-vasilev-prime** [comment]
Oh I'll try that 😁

**Comment by StanevPrime** [comment]
> You have to remove the `^`: `widget_toolkit_pin: 0.2.0`
> 
> Fun fact: writing it as `^0.2.0` is the same as `>=0.2.0 <0.3.0`, so essentially telling it to fetch the latest non-breaking update... which in this case is 0.2.1, which you helped publish 2 days ago 😆

Please create a ticket and fix the issue in the widget_toolkit_pin accordingly. This ticket will be blocked until the other issue is not resolved.

**Comment by JvnSlv** [comment]
Tested, and can confirm that all the tests in the generated projects are passing
