### ISSUE TITLE
Re-record Github tutorial parts to match latest rx_bloc_cli functionality

### ISSUE THREAD

**Issue by DDavidPrime** [Prime-Holding/rx_bloc#736]
Due to some changes, we need to update the existing video guide regarding the Github CI/CD functionality of the generated rx_bloc_cli project.

ACs:
- [x] Re-record section with updated environment variables

**Comment by nikolay-vasilev-prime** [comment]
@DDavidPrime  I tested it and it works! I have one small comment. It is maybe worth mentioning that after the files are encrypted, the original ones should be deleted before pushing the code. It is logical that this should be done, but it's easy to miss while following the tutorial. It can be mentioned in the MD file as well.

**Comment by StanevPrime** [comment]
- The credential files are git-ignored.
- There is a step in the CD pipeline, which deletes the encrypted file to ensure non of them remains in the cloud.

@DDavidPrime, please confirm

**Comment by DDavidPrime** [comment]
I think @nikolay-vasilev-prime meant to remove the original files locally. But I believe this is not necessary, as they are excluded from the source control. Having them locally makes no impact to the user. But on the other hand , yes, @StanevPrime is right. The files are deleted when the pipeline is done.

**Comment by DDavidPrime** [comment]
@nikolay-vasilev-prime Yes, that's correct. The urls are only accessible to users with enough privilege (such as `Owner` and `Admins`). 

I think this was mentioned in the video. However, should we include this information in the Readme? @StanevPrime

**Comment by DDavidPrime** [comment]
Closing as Done.
