### ISSUE TITLE
Authentication Matrix (MFA) improvements

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#740]
As a developer I want to have MFA, which methods are dynamically configurable from the API

ACs

- [x] BE auth methods dynamic configuration
  - [x] Refactored models
  - [x] Refactored REST API
- [x] Stream-based clear and concise Flutter API
  - [x] Designed Flutter API
  - [x] Implemented Flutter API
- [x] Library decoupled, observer-based side effects
- [x] Applied SOLID principles
- [x] Improved error handling
- [x] Reduced time for implementing new authentication methods
- [x] Reduced time for implementing a request and response payload
- [x] Documentation
  - [x] Rest API Specification
  - [x] C4 Diagram
  - [x]  Client documentation
    - [x] How to add a authentication method
    - [x] How to add an action
 - [x] Unit tests

**Comment by DDavidPrime** [comment]
After some testing in the `develop` branch, some part of the MFA functionality seems to be broken. After completing the pin code and OTP screens in either of the examples (see attachment in GDrive, video is larger than 10mb) the screen turns black. After checking the logs, it seems a page was popped, while it was the last on stack.
The project was generated fresh from the latest (unpublished) version of rx_bloc_cli including the MFA functionality. The project was tested on iOS Simulator.

Video Attachment:
https://drive.google.com/file/d/1H7XKZzqUS_9AhJWHjoNkxsBNZqp3gZ-Y/view?usp=sharing
