### ISSUE TITLE
Remove Dependency on flutter/cupertino Library from rx_bloc_list models

### ISSUE THREAD

**Issue by JvnSlv** [Prime-Holding/rx_bloc#749]
The rx_bloc_list package currently has a dependency on the flutter/cupertino library within its models. However, models are part of the business layer and should be UI-independent.

Having this dependency goes against the principle of separating the business logic from the UI layer. This dependency should be removed to maintain a clean architecture and ensure the models remain decoupled from any UI-specific libraries.

Proposed Solution:
Refactor the models to remove any references to flutter/cupertino and ensure they remain UI-independent.
Move file `paginated_list_extensions.dart` from `lib/src/models` to `lib/src/extensions`

ACs:
- [x] Move `PaginatedListStreamExtensions` and `PaginatedListSnapshotExt` which depend on `cupertino` to `extensions` directory
  - [x] Remove them as part of `PaginatedList` model
  - [x] Replace `cupertino` with just `widgets` from the Flutter package
- [x] Move `PaginatedListBinder` extension to `PaginatedList` model due to usage of private `_backupList` field
- [x] Export package `extensions` separately from `models`
- [x] Fix imports
- [x] Update version number & changelog

**Comment by JvnSlv** [comment]
@StanevPrime

**Comment by StanevPrime** [comment]
The proposed solution looks good to me. Feel free to add ACs and additional one for updating the versions. See this ticket for more details https://github.com/Prime-Holding/widget_toolkit/issues/109#issue-2415508838
