### ISSUE TITLE
Improve CD command to accept key details to generate desired files

### ISSUE THREAD

**Issue by nikolay-vasilev-prime** [Prime-Holding/rx_bloc#784]
As a developer I would like to be able to add key alias and passwords to the distribution command so it will be able to generate the files automatically.

In the current solution I need to go to every file separately and update it and I would like to know if this can be improved.

Also an option to the command can trigger kaytool to generate `.jks` file.

Estimate: 4h

**Comment by StanevPrime** [comment]
Not needed
