### ISSUE TITLE
On newly generated project with rx_bloc_cli there's non compilable error

### ISSUE THREAD

**Issue by nikolay-vasilev-prime** [Prime-Holding/rx_bloc#787]
After generating a new project with `rx_bloc_cli` in `lib/lib_router/router.dart` in `_pageRedirections` `pathInfo` calls `findMatch` which expects `URI` but receives a string instead.

The fix is to remove the `.toString()` function at the end.

<img width="799" alt="image" src="https://github.com/user-attachments/assets/9582b232-5b4c-468c-8b3a-37152f111a65">

**Comment by StanevPrime** [comment]
@nikolay-vasilev-prime feel free to fix this issue

**Comment by nikolay-vasilev-prime** [comment]
Merged with #788
