### ISSUE TITLE
Update Realm Configuration & Implement App Distribution

### ISSUE THREAD

**Issue by JvnSlv** [Prime-Holding/rx_bloc#804]
This issue addresses two major requirements for the TodoApp:

   

- [x]  Updating the Realm configuration from flexibleSync to local.
  - [x] Replace all instances of Realm configuration.flexibleSync with Realm configuration.local.
  - [x] Ensure that the app runs seamlessly using local configuration 
    - [x] with and without an internet connection.
    - [x] Regardless whether the application can connects to the Rest API 
    Note: When deployed to TestFight the API won't be accessible
- [x]   Implementing app distribution for TestFlight and Google Play Internal Testing.
  - [x] Implement app distribution using Fastlane and GitHub Actions

**Comment by StanevPrime** [comment]
Blocked due to missing `service-account-key.json`
