### ISSUE TITLE
Implement a script that runs integration (patrol) tests

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#816]
As a QA engineer I need a script that runs the integration (patrol) tests by prompts so that I don't need to populate the patrol executable arguments by myself

AC
- Prompts
  - test set
  - env
  - ~tag~
  - ~platform~
  - language
  - device
- Removed Scripts / Run Configurations
  - Run E2E test - dev
  - Run E2E test - prod
  - Run E2E test - sit
  - Run E2E test - uat
-  Added Run Configuration
   - Run Integration (Patrol) Tests

An example 

```
Fetching device list...done.
Select a test set:
	(1) all (default)
	(2) regression tests
	(3) negative tests
	(4) positive tests
1
Select an environment:
	(1) DEV
	(2) SIT (default)
	(3) UAT

Select a platform:
	(1) Android
	(2) iOS
1
Select a language:
	(1) bg (default)
	(2) en

Select a device:
	(1) sdk gphone64 arm64 (emulator-5554)
	(2) iPhone 15 Pro (62E75182-5EBE-4401-A992-2BAC21D9E79E)
	(3) macOS (macos)
	(4) Mac Designed for iPad (mac-designed-for-ipad)
1
```

Remaining estimate: 4h

**Comment by StanevPrime** [comment]
@kostadin-damyanov-prime please help @JvnSlv handling the tags in the patrol integration tests

**Comment by DDavidPrime** [comment]
Once #833 is merged, we can move this ticket too.

**Comment by DDavidPrime** [comment]
Tested and can confirm that the functionality is as described in this ticket.

**Comment by GoranPrime** [comment]
Tested & confirmed everything is working as expected
