### ISSUE TITLE
Better organization of showcase features in rx_bloc_cli generated projects

### ISSUE THREAD

**Issue by DDavidPrime** [Prime-Holding/rx_bloc#829]
Originating from [this comment](https://github.com/Prime-Holding/rx_bloc/pull/827#discussion_r1795135733), as a developer I want to have a better organization of the showcase features in projects generated using the `rx_bloc_cli` package. 

The current implementation includes many different showcase features placed inside the starting page. With each new showcase added, a new option is included to the home page which increases the number of navigation bar items (going against suggested UX). The goal of this ticket is to implement a showcase features page from where you can select and check out individual showcases, while making space for any other upcoming features.

ACs:
- [x] Implement showcase page where all showcase features reside (ETA: 2h)
  - [x] Conditionally add options on the showcase page based on the project configuration
- [x] The following showcases should be part of the showcase page (ETA: 7h)
  - [x] Counter example (feature_counter)
  - [x] Widget toolkit (feature_widget_toolkit)
  - [x] Deeplinks (feature_deeplinks)
  - [x] QR Code scanner (feature_qr_scanner)
  - [x] MFA (feature_mfa): only the showcase part
  - [x] OTP (feature_otp)
  - [ ] ~Social Logins (feature_social_logins)~
- [x] Add showcase page to app bottom navigation (ETA: 1h)
  - [x] Remove all showcase features from bottom navigation

Estimate (total): 10h

**Comment by StanevPrime** [comment]
@JvnSlv be aware of this ticket

**Comment by DDavidPrime** [comment]
Tested the ticket and can confirm the implementation in the generated apps is matching the ACs.
