### ISSUE TITLE
Research golden test packages as replacement for the golden_toolkit package

### ISSUE THREAD

**Issue by JvnSlv** [Prime-Holding/rx_bloc#830]
The golden_toolkit package, currently used within the rx_bloc ecosystem for golden tests, has been discontinued and is no longer maintained. To ensure ongoing stability and support for golden tests, golden_toolkit needs to be replaced with the alchemist package, which is an active and well-supported alternative.

**Comment by StanevPrime** [comment]
@DDavidPrime please review what other options we have other than the alchemist package.

**Comment by DDavidPrime** [comment]
@StanevPrime After conducting the initial research these are the results:

1. Alchemist (https://pub.dev/packages/alchemist):
- Regularly updated package and most popular package
- Biggest gamut of options - in regards to other listed packages
- Uses `_golden_test.dart` format for goldens generation
- Separates platform (Local) and CI golden tests
- Uses `goldenTest` function and `GoldenTestGroup` to group scenarios
- Generated in `goldens/ci/` or `goldens/{platform}}/` relative to the test file
- Automatic and custom image sizing (no device setup)

2. Golden screenshot (https://pub.dev/packages/golden_screenshot):
- Frequent updates
- Provides dozen of utilities
- Lower popularity
- Uses `tester.expectScreenshot` for comparing screenshots
- Customization of devices and their properties (resolution, pixel ration, goldens subfolder)
- Customization of frames which are wrapped around the golden

3. BC Golden Plugin (https://pub.dev/packages/bc_golden_plugin):
- Young package (month ago, at the time of writing) but maintained
- Made with the idea of developing agains a reference design (in Figma)
- Customization of window and its properties (size, pixel density,...)
- Setup requires a bit more work and uses similar approach to writing unit tests

4. Golden Variant (https://pub.dev/packages/golden_variant):
- Very young package (2-3 days ago, at the time of writing)
- Has many utilities (devices,sizes,LTR, keyboard displaying)
- Widgets are manually pumped using `tester.pumpWidget`

**Comment by StanevPrime** [comment]
@DDavidPrime, olease evaluate the option to use the package:flutter (https://github.com/flutter/flutter/blob/master/docs/contributing/testing/Writing-a-golden-file-test-for-package-flutter.md) to minimise the dependencies we have in the rx_bloc_cli generated projects

**Comment by DDavidPrime** [comment]
Oh and also @nikolay-vasilev-prime , custom pumps shouldn't be an issue because as per their documentation they are supported:

![Screenshot 2024-10-29 at 14 58 21](https://github.com/user-attachments/assets/22f84b02-43e5-4d5b-9c2d-7be5e8714a04)

**Comment by nikolay-vasilev-prime** [comment]
Perfect. It will be nice to check it with some of our existing tests 😄
