### ISSUE TITLE
Generated rx_bloc_cli project goldens fail on non-linux machines

### ISSUE THREAD

**Issue by nikolay-vasilev-prime** [Prime-Holding/rx_bloc#831]
As a developer I would like when I create a project with rx_bloc_cli, the generated golden tests to succeed!

Currently the when generating project with rx_bloc_cli the tests that come out of the box fail on non-linux machines, because they are generated from linux machine.

AC:

- [ ] When creating project with rx_bloc_cli and execute "Run All Tests", all tests should succeed!

**Comment by DDavidPrime** [comment]
Not reproducible with projects using `alchemist` package.

Feel free to reopen the ticket in case this issue reappears again.
