### ISSUE TITLE
IntelliJ plugin: Add support for golden tests using alchemist package

### ISSUE THREAD

**Issue by DDavidPrime** [Prime-Holding/rx_bloc#846]
As a developer I want the plugin to be able to generate tests using the [alchemist package](https://pub.dev/packages/alchemist) as an ongoing effort to replace the discontinued golden_toolkit package. Support for the `golden_toolkit` tests will continue until announced otherwise.

ACs:
- When generating tests, add a dropdown that would allow to select between two options: `golden_toolkit` and `alchemist`
- The `alchemist` option should be preselected (and treated as the default one)
- Existing functionality should remain untouched
- Upon confirming, generate tests using the selected format

Estimate:
- (TBA)

**Comment by StanevPrime** [comment]
@PVGeorgievPrime, could you please provide an estimate for this ticket ?

**Comment by StanevPrime** [comment]
@DDavidPrime, could you please test the changes ?

**Comment by DDavidPrime** [comment]
Confirming that it is working as expected. The newest version generates code for both alchemist and golden toolkit, depending on the selection.

**Comment by RomanovaPrime** [comment]
Performed tests: 

 - Generate golden test on a single file ending with “page” - successfully create folder with test and factory files
 - Trying to create tests for folder, but such exist - Provide user friendly message
 - Generate tests for feature folder prompt select a package for golden tests
 - alchemist package is preselected
 - Works for bought packages in a consistent  way
