### ISSUE TITLE
Update github workflows to use up-to-date dependencies

### ISSUE THREAD

**Issue by DavidDWiser** [Prime-Holding/rx_bloc#869]
As a developer I want my pipelines in Github to be up-to-date using latest dependencies (see attachment below).

ACs:
- [x] Update github workflows generated by the `rx_bloc_cli` command to use latest dependencies
- [x] Update workflows in the `rx_bloc` github repository
- [x] Update the [distribution-example](https://github.com/Prime-Holding/rx_bloc_cli-distribution-example) project 

Note: Same applies to the `widget_toolkit` repo which is tracked in [this ticket](https://github.com/Prime-Holding/widget_toolkit/issues/137).

<details>
  <summary>Attachment: Deprecation notice</summary>
  <br/>

![Image](https://github.com/user-attachments/assets/6967dca4-4ccc-426f-80d0-2ef84aef7e84)
  
</details>

**Comment by DDavidPrime** [comment]
Even though I was working on this, I believe we can move this to `Tested` or even `Done` as it's been out for quite some time. This ticket addresses some smaller changes in the workflows which have been working since the ticket has been merged.
