### ISSUE TITLE
Biometrics fails to verify pin code

### ISSUE THREAD

**Issue by JvnSlv** [Prime-Holding/rx_bloc#886]
The biometrics feature does not work when trying to verify the pin code with fingerprint or FaceID.

**Steps to Reproduce**

- Create a generated project.
- Navigate to the profile page and enable biometrics.
- Create a PIN code in the profile page.
- Wait for the timeout and attempt to verify the PIN code using biometrics.

**Expected Behavior**
Biometric authentication should verify the PIN code successfully.

**Actual Behavior**
The pin code is sent to the backend via the `/pin/verify` endpoint for verification, but the biometric authentication does not trigger this request, resulting in a failure to verify. Biometric authentication is not integrated with this workflow

**Comment by GoranPrime** [comment]
Tested & confirmed working
