### ISSUE TITLE
Generated project should hide biometrics on devices that don't have biometrics

### ISSUE THREAD

**Issue by nikolay-vasilev-prime** [Prime-Holding/rx_bloc#888]
As a developer I would like devices that don't have biometrics to not have UI for biometrics.

ACs:
- [ ] Hide biometrics on Pin Code screen
- [ ] Hide the biometrics toggle form profile screen

**Comment by GoranPrime** [comment]
Should I move this task over to "Done", or do we plan to implement a separate column such as "Not Planned"?

@StanevPrime

**Comment by StanevPrime** [comment]
Move the ticket to Done
