### ISSUE TITLE
Update Generated Project Server to Use HTTP v1 FCM API

### ISSUE THREAD

**Issue by JvnSlv** [Prime-Holding/rx_bloc#907]
The generated project's server uses the deprecated legacy FCM API. The current implementation no longer works due to the deprecation of the legacy API.

This should be updated to the newer HTTP v1 API for Firebase Cloud Messaging, as recommended by Google

Reference: [Migrate from legacy FCM APIs to HTTP v1](https://firebase.google.com/docs/cloud-messaging/migrate-v1)

**Comment by GoranPrime** [comment]
Tested & confirmed working. I have 2 suggestions:
1. We should update the last note in the [README](https://github.com/Prime-Holding/rx_bloc/blob/develop/packages/rx_bloc_cli/example/README.md#push-notifications) to give usage instructions for the new approach (providing the service account through `dart --define etc` in start_server.sh)

2. The docs for [clientViaServiceAccount](https://pub.dev/documentation/googleapis_auth/latest/auth_io/clientViaServiceAccount.html) mention this:
> The user is responsible for closing the returned HTTP Client. Closing the returned Client will not close baseClient.

With that being said, I believe we should call `client.close()` in `PushNotificationsController._getAccessToken` before returning the access token, just to make sure we're following best practices and not accidentally filling up memory with loose HTTP clients 😃

**Comment by GoranPrime** [comment]
Tested again & confirmed working after the changes
