### ISSUE TITLE
Update Example Projects for Flutter 3.27 Compatibility

### ISSUE THREAD

**Issue by JvnSlv** [Prime-Holding/rx_bloc#914]
With the release of Flutter 3.27, several new features and updates were introduced that can enhance the functionality and performance of our example projects. This issue tracks the update of the following example projects:

- [ ]     TodoApp
- [ ]     RemindersApp

**Comment by GoranPrime** [comment]
From what I can see, RemindersApp hasn't been updated yet.
I'm also having an issue running BookingApp on Android:
<img width="532" alt="image" src="https://github.com/user-attachments/assets/e1046009-e68e-4af1-81f6-ebad99c5cd71" />

**Comment by GoranPrime** [comment]
Tested & confirmed working
