### ISSUE TITLE
QR Code camera permission is not working on iPhone.

### ISSUE THREAD

**Issue by nikolay-vasilev-prime** [Prime-Holding/rx_bloc#921]
When generated project from rx_bloc_cli is running on iOS device and QR code, camera permission is not requested, but it navigates to settings instead, where no permission can be granted!

This should be tested on a real device, because it cannot be tested in Simulator.

AC:

- [ ] When I try to use QR code functionality from the Showcase on an iPhone I need to have a permission request dialog on first try. 

If the ticket is related to pincode widget toolkit move it to the correct project!

**Comment by GoranPrime** [comment]
Tested & confirmed working on real device
