### ISSUE TITLE
On Android the testapp gets stuck on the initial screen.

### ISSUE THREAD

**Issue by nikolay-vasilev-prime** [Prime-Holding/rx_bloc#922]
The testapp gets stuck on the initial screen and cannot proceed on Android.

<img width="380" alt="image" src="https://github.com/user-attachments/assets/e1504850-95a3-4ed7-8ed7-cb059d26d97b" />

**Comment by nikolay-vasilev-prime** [comment]
Addin `--no-enable-impeller` to the run command, fixes the issue. @StanevPrime do you think that we need to add this to all the scripts?

**Comment by nikolay-vasilev-prime** [comment]
It turns out that the new version of flutter and impeller, doesn't work on Android Pre-Release of VanillaIceCream so in order to make it work you need to make sure to run API version 35 with Google Play, otherwise you will be stuck on splash screen!

**Comment by DDavidPrime** [comment]
I've checked with Android API 33, 34 and 35 and was unable to reproduce this. I believe this has been properly addressed.
